// This file is automatically generated. Do not modify it manually.
// For more information, see the Firebase JS SDK documentation:
// https://firebase.google.com/docs/web/setup#add_firebase_to_your_app

export const firebaseConfig = {
  apiKey: "AIzaSyBKyhG5uHwWl23-6T6ueiYiGBhiSzTbJPA",
  authDomain: "studio-544175764-b8623.firebaseapp.com",
  projectId: "studio-544175764-b8623",
  storageBucket: "studio-544175764-b8623.appspot.com",
  messagingSenderId: "261401370625",
  appId: "1:261401370625:web:0a840806e11c944efe2000",
};
